title: Praveen Chandrashekar
description: Centre for Applicable Mathematics, TIFR, Bangalore
show_downloads: false
google_analytics:
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme
- jekyll-feed
